<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IMBridge.Tests</RootNamespace>
    <AssemblyName>IMBridge.Tests</AssemblyName>
    <!-- 测试工程不发布 AOT，仅验证桥接核心逻辑 -->
    <PublishAot>false</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IMBridge\IMBridge.csproj" />
  </ItemGroup>

</Project>
